version: '3.8'
services:

  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/city_population
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network


  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - city_population:/data/db
    networks:
          - node-network

volumes:
  city_population:

networks:
  node-network:
    driver: bridge